group = sqlbox
id = pg
smsbox-id = sqlbox1
bearerbox-host = host.docker.internal
bearerbox-port = 13001
smsbox-port = 13002
sql-log-table = front_sms_log
sql-insert-table = front_sms_insert
log-level = 4

include = "/etc/kannel/db.conf"