group = core
dlr-storage = pgsql

group = opensmppbox
opensmppbox-id = opensmppbox1
opensmppbox-port = 14567
bearerbox-host = host.docker.internal
bearerbox-port = 14001
log-level = 4
route-to-smsc = FAKE1
our-system-id = 
use-systemid-as-smsboxid = true
smpp-logins = "/etc/kannel/smsc-users.txt"

include = "/etc/kannel/db.conf"

group = dlr-db
id = pg
table = smsc_smpp_dlr
field-smsc = smsc
field-timestamp = timestamp
field-destination = destination
field-source = source
field-service = service
field-url = url
field-mask = mask
field-status = status
field-boxc-id = boxc_id